dist: xenial
language: c
sudo: required
notifications:
  email:
  - btc@openInWorld.com
jobs:
  fast_finish: true
  include:
  - stage: Stack builds
    env: ARCH="mingw32x86-on-linux" FLAVOR="squeak.stack.spur"
install: "./scripts/ci/travis_install.sh"
before_script: "$CHROOT ./scripts/ci/travis_build.sh"
script: "./scripts/ci/travis_test.sh"
after_success: "(cd deploy && ./filter-exec.sh pack-vm.sh)"
deploy:
  provider: releases
  api_key:
    secure: qaBE17pIFvpKKNMrSve79NwmMyh5l6R6cA/iuSlcnCpEC5fxfrYBBDcmLxDXUtrLh5VxcRBPzVFVoq2vQDPI1GR5I7yeqpsnR7qSOYJdkjYnMl2yl17CUqQbQe7JGdbkjRfTnM+34Emf93+CpRTaKfIQ+Mbv6w/YUIuM9JBATVhMrhgf7qwaWR93qM1dDL5Vg5xyNqOTz4ImLjucxrS+TKnfSw8gul41t8H/QEmVQN4CYz4cZ0duDTamhG5NB7tx/DcJfy0NOlEWjlgWmwwH8IbgXzEMqc5vaiMOX1lSTs6KP2biH9wTHiNKcGrhVaqLGKTc4V0ntJYNzo+fxoFJr+FrWxtGw1V8Z0SpWOEZK68DWVE+5haHC1u97AgnKjJMNuxUJV8xSnWTaVPcLhaK2H/bm2i7T1BECcWFTImPd6I4dyo6bm6go5FA4ZYXRzyisTWAiu3pqzwIQgY5XdEIvSBI0DP8Q7BekIvO4WdTTlOjHcYKb09+hOSi1D0jnKzN3BKutdkW7eM7HNUWZ8Uojg23Cpwh9SafGf5NBoT80NUtOJO8HwZIoEdlsxotm01Ra7exFpsdFJMwAKSHlrUVtAGNbEuqT49Plm6VDA+obwWps96Ov4H5zVeHjZHZpdgZUPTtMXUAmk9fkxwAM1umTlETw4cLsrXAfCZBFrgCR/k=
  file: xx.txt
  skip_cleanup: true
  on:
    tags: true
