dist: xenial
language: c
sudo: required
notifications:
  email:
  - btc@openInWorld.com
jobs:
  fast_finish: true
  include:
  - stage: Stack builds
    env: ARCH="mingw32x86-on-linux" FLAVOR="squeak.stack.spur"
install: "./scripts/ci/travis_install.sh"
before_script: "$CHROOT ./scripts/ci/travis_build.sh"
script: "./scripts/ci/travis_test.sh"
after_success: "(cd deploy && ./filter-exec.sh pack-vm.sh)"
deploy:
  provider: releases
  api_key:
    secure: fLxvmoMW6Zr50X48kQr8mxYBBT/IHdaczMQIuz8Txi0liba0XK132mYnRZdaymHE9w50xBisRb67WfJoH3odR450cxbIkRB7wRT2hEnvC62IQzPh6HrkZDzUkN3v/resoX0lkx2sbrxmI7WvpGCaRjexWg+dmMg0Wvc2lgbnMNWNsYABddXQ0vltSY1ZZipodR+ygOMIwDStr2rKT0xTgGzgHdcIVGw1t07q6wgPh3FeGOHPCNsE9v3LTxyn+ZSG8GhMsMXklYSchNl8pytXYRe+WmY49MjGSFPpWpJQfSrTGrGpPDtMNu6CoS1/LbNNTxlmcbLEUE9dLoFi8N974yCiwO7h9lEQ2/94N8Nr7pV2ZLlH4yV7ZvdMgYcH5CBhEwvqS35hzjqpHSNrCbBa1/Um4ycdZCRCnqR7dlQuHkOKUWBp8pnx1QjguyOTdfFPjMN6CDzVRj9I6q6SPzCfEuY+3dUpxbf6O9LkX3xTK/rC4/r9OHZ94Ws4Gj9GgMp0U0wL8I7HEUDptyNpX2wOKk+Du9wNACZu2p3yCmdInky4AcZZJ3iaHV7ju3a+OPY9eu9VErP+uidwf1pADy0/GwVZotEu2zA30zquzyM0rENkBlkYsL57+Ex6sphmwj60Z8FAdHt28R+ZPAq27IuW3mSQWMBt5/OWN/E+2KzuklU=
  file: xx.txt
  on:
    repo: bencoman/opensmalltalk-vm
