language: c

sudo: required

osx_image:
  - xcode7.3

dist: trusty

addons:
    apt:
      update: true

cache:
  directories:
  - armchroot
  - .thirdparty-cache

#notifications:
#  slack:
#    secure: gyekIJqPdx7SxqpugvtpY5mZSg54oFkFJ+DKBPILtjyI/sDhcSwT9GwY/zoHoYkoHrPLepDxyPgkAC8JCcTiAcxOazq5zlVva6SoQRjlDnC64oCYvOj/2giuYkXLXnwvj8mIINEgXzEvLdalpHwazsY0fzKNFM1mdrkPolmf2CvaNbKCGkiagsjrxJHEEB4tLcUP4ArqVE6wb+20HXoMKlHccgCFvN67bYJrTXDnuhEgKMooQRFv0yVoimckdRn1amvIgljavPwv2yHX+V1roneyi90e4ri9AT2sROeRprGnaib9Z8p+/mgWIUnTLL7pjbNHhtvZptsj3xjanWy1Bt/4MMewTWN4REE/KKxLp79CQvGNR+Ki7mF2UpgYUtxHYpFNIGNF9VomwnfWAuYdGDAYAGY3S1W12RPo37CC7RP/lPM96L6ypW41FoQKlnhzm+StJV+mlI5C1jQBU2WKoVhaKXJpraX2mUJXyN8ilYDo7PrJe0SRLH6J2WwPM5Z/RdscBDEGAR4RhZnn++1IE7e1gZPJB4NZH/3wLBwDhz8S4kB/GB32/rz3ZaftCf2+XjAZXzF3SroUCZ/MWZPGrwchEkU/3z1Tm8FTbELxZk1rSYpdLwVnXYooo5vggqjgAZvmlTerJuufl5lOkXT44PynZAvE+I+MrD04DpKuH0w=

#notifications:
#  email:
#    - vm-dev@lists.squeakfoundation.org

stages: # order of...
  - Production
  - Coverage
  - Experimental
  - Other



# Sections 'os:' and 'env:' are cross-tabulated to form the 'Coverage' matrix
# 'Production' jobs are pulled out of that matrix into their own section

stage: Coverage

os:
  -       linux
  -       osx
#  -       windows

env: [
    &Squeak32    "BUILD=32x86/squeak.cog.spur     TESTIMAGE=Squeak32-5.1",
    &Pharo32     "BUILD=32x86/pharo.cog.spur      TESTIMAGE=Pharo32-5.0  HEATBEAT=threaded",
                 "BUILD=32x86/newspeak.cog.spur   TESTIMAGE=refer_newspeakBootstrap.sh",
                 "BUILD=32x86/squeak.cog.v3       TESTIMAGE=Squeak32-4.6",

                 "BUILD=32x86/squeak.cog.spur     TESTIMAGE=Squeak32-5.1",
                 "BUILD=32x86/pharo.cog.spur      TESTIMAGE=Pharo32-5.0  HEATBEAT=threaded",
                 "BUILD=32x86/newspeak.cog.spur   TESTIMAGE=refer_newspeakBootstrap.sh",
                 "BUILD=32x86/squeak.cog.v3       TESTIMAGE=Squeak32-4.6",

    &Squeak64    "BUILD=64x64/squeak.cog.spur     TESTIMAGE=Squeak32-5.1",
    &Pharo64     "BUILD=64x64/pharo.cog.spur      TESTIMAGE=Pharo32-5.0  HEATBEAT=threaded",
                 "BUILD=64x64/newspeak.cog.spur   TESTIMAGE=refer_newspeakBootstrap.sh",

                 "BUILD=64x64/squeak.cog.spur     TESTIMAGE=Squeak32-5.1",
                 "BUILD=64x64/pharo.cog.spur      TESTIMAGE=Pharo32-5.0  HEATBEAT=threaded",
                 "BUILD=64x64/newspeak.cog.spur   TESTIMAGE=refer_newspeakBootstrap.sh",
]

matrix:
  allow_failures:
    - stage: Coverage
    - stage: Experimental
  # Define the 'Production' jobs that are excluded from the 'Coverage' matrix
  exclude: [
    &P01 { "os":"linux", "env":*Pharo64  },
    &P02 { "os":"osx",   "env":*Pharo64  },
    &P03 { "os":"linux", "env":*Squeak64 },
    &P04 { "os":"osx",   "env":*Squeak64 },

    &P05 { "os":"linux", "env":*Pharo32  },
    &P06 { "os":"osx",   "env":*Pharo32  },
    &P07 { "os":"linux", "env":*Squeak32 },
    &P08 { "os":"osx",   "env":*Squeak32 },
  ]

jobs:
  fast_finish: true
  include:
  # Put 'Production' jobs in their own stage using alias from 'excude:' section
  - stage: Production
    <<: *P01
  - stage: Production
    <<: *P02
  - stage: Production
    <<: *P03
  - stage: Production
    <<: *P04
  - stage: Production
    <<: *P05
  - stage: Production
    <<: *P06
  - stage: Production
    <<: *P07
  - stage: Production
    <<: *P08

#  - { "stage":"Experimental",  "os":"osx",    "env":"BUILD=32x86/pharo.sista.spur"                                                   }
#  - { "stage":"Experimental",  "os":"linux",  "env":"BUILD=32x86/squeak.sista.spur"                                                  }
#  - { "stage":"Experimental",  "os":"linux",  "env":"BUILD=32x86/squeak.sista.spur     TESTFAIL=1"                                   }
#  - { "stage":"Experimental",  "os":"linux",  "env":"BUILD=32x86/pharo.sista.spur      HEARTBEAT=threaded",    "compiler": "clang"   }
#  - { "stage":"Experimental",  "os":"linux",  "env":"BUILD=32x86/pharo.sista.spur      HEARTBEAT=itimer",      "compiler": "clang"   }
#  - { "stage":"Experimental",  "os":"osx",    "env":"BUILD=32x86/pharo.cog.spur.lowcode"                                             }
#  - { "stage":"Experimental",  "os":"osx",    "env":"BUILD=64x64/pharo.cog.spur.lowcode"                                             }
#  - { "stage":"Experimental",  "os":"osx",    "env":"BUILD=32x86/pharo.stack.spur.lowcode"                                           }
#  - { "stage":"Experimental",  "os":"osx",    "env":"BUILD=64x64/pharo.stack.spur.lowcode"                                           }

#  - { "stage":"Other",         "os":"linux",  "env":"BUILD=32ARMv6/newspeak.cog.spur   CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }
#  - { "stage":"Other",         "os":"linux",  "env":"BUILD=32ARMv6/newspeak.stack.spur CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }
#  - { "stage":"Other",         "os":"linux",  "env":"BUILD=32ARMv6/squeak.cog.spur     CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }
#  - { "stage":"Other",         "os":"linux",  "env":"BUILD=32ARMv6/pharo.cog.spur      CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }
#  - { "stage":"Other",         "os":"linux",  "env":"BUILD=32ARMv6/squeak.stack.spur   CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }
#  - { "stage":"Other",         "os":"linux",  "env":"BUILD=32ARMv6/squeak.stack.v3     CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }
#
#    # Putting quicker builds last makes the overall stage faster
#  - { "stage":"Other",         "os":"linux",  "env":"BUILD=32x86/pharo.cog.spur        HEARTBEAT=itimer" }
#  - { "stage":"Other",         "os":"linux",  "env":"BUILD=64x64/pharo.cog.spur        HEARTBEAT=itimer" }
#
#  ]

